        public class Main {
            public static void main(String[] args) {
                System.out.println("Задача 1");
                var dog = 8.0;
                System.out.println(dog);
                var cat = 3.6;
                System.out.println(cat);
                var paper = 763789;
                System.out.println(paper);
                System.out.println("Задача 2");
                dog = dog + 4;
                System.out.println(dog);
                cat = cat + 4;
                System.out.println(cat);
                paper = paper + 4;
                System.out.println(paper);
                System.out.println("Задача 3");
                dog = dog - 3.5;
                System.out.println(dog);
                cat = cat - 1.6;
                System.out.println(cat);
                paper = paper - 7639;
                System.out.println(paper);
                System.out.println("Задача 4");
                var friend = 19;
                System.out.println(friend);
                friend = friend + 2;
                System.out.println(friend);
                friend = friend / 7;
                System.out.println(friend);
                System.out.println("Задача 5");
                var frog = 3.5;
                System.out.println(frog);
                frog = frog * 10;
                System.out.println(frog);
                frog = frog / 3.5;
                System.out.println(frog);
                frog = frog + 4;
                System.out.println(frog);
                System.out.println("Задача 6");
                var boxerMass1 = 78.2;
                var boxerMass2 = 82.7;
                var totalWeight = boxerMass1 + boxerMass2;
                System.out.println("Масса двух боксеров равна " + totalWeight + " кг!");
                var differentWeight = boxerMass2 - boxerMass1;
                System.out.println("Разница в весе составляет " + differentWeight + " кг!");
                System.out.println("Задача 7");
                var remainderWeight = boxerMass2 % boxerMass1;
                System.out.println("Разница между весами " + remainderWeight + " кг!");
                System.out.println("Задача 8");
                var generalHours = 640;
                var peopleHours = 8;
                var totalPeople = generalHours / peopleHours;
                System.out.println("Всего работников в компании - " + totalPeople + " человек");
                totalPeople = totalPeople + 94;
                var peopleHours2 = generalHours / totalPeople;
                System.out.println("Если в компании работает " + totalPeople + " человека, то всего " + peopleHours2 + " часа работы может быть поделено между сотрудинками");
            }
        }
